[package]
name = "elk"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delf = { path = "../delf" }
region = "2.2"
mmap = "0.1"
carpenter = {path = "../../carpenter"}

[features]
